# Generated by Django 2.0.1 on 2018-02-11 12:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('password', models.CharField(blank=True, max_length=150, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('detail', models.CharField(blank=True, max_length=300, verbose_name='detail content')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
            ],
            options={
                'db_table': 'admin_user',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('cd', models.CharField(help_text='国コード', max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='国名(英語表記)', max_length=200)),
                ('detail', models.CharField(default='', help_text='詳細', max_length=200)),
                ('memo', models.CharField(default='', help_text='メモ（内部用）', max_length=500)),
            ],
            options={
                'db_table': 'country',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cd', models.CharField(help_text='貨幣コード', max_length=20)),
                ('name', models.CharField(help_text='貨幣の名称', max_length=20)),
                ('detail', models.CharField(help_text='詳細情報', max_length=200, null=True)),
                ('est_date', models.DateTimeField(help_text='施行日')),
                ('country', models.ForeignKey(help_text='国', on_delete=django.db.models.deletion.CASCADE, to='common.Country')),
            ],
            options={
                'db_table': 'currency',
            },
        ),
        migrations.CreateModel(
            name='Money',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(verbose_name='発行日時')),
                ('name', models.CharField(max_length=50)),
                ('alias', models.CharField(help_text='貨幣名称の別名（カナ表記など）', max_length=20, null=True)),
                ('price', models.IntegerField(default=1)),
                ('image', models.CharField(help_text='選択肢名', max_length=200)),
                ('detail', models.CharField(default='', help_text='選択肢名', max_length=200)),
                ('currency', models.ForeignKey(help_text='貨幣情報', on_delete=django.db.models.deletion.CASCADE, to='common.Currency')),
            ],
            options={
                'db_table': 'money',
            },
        ),
        migrations.CreateModel(
            name='MoneyType',
            fields=[
                ('cd', models.CharField(help_text='貨幣コード', max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='貨幣名称', max_length=20)),
                ('alias', models.CharField(help_text='貨幣名称の別名（カナ表記など）', max_length=20, null=True)),
                ('prefix', models.CharField(help_text='金額の前表記', max_length=20)),
                ('suffix', models.CharField(help_text='金額の後表記', max_length=20)),
                ('detail', models.CharField(help_text='詳細情報', max_length=200, null=True)),
                ('country', models.ForeignKey(help_text='言語別の貨幣タイプ', on_delete=django.db.models.deletion.CASCADE, to='common.Currency')),
            ],
            options={
                'db_table': 'money_type',
            },
        ),
        migrations.CreateModel(
            name='Verify',
            fields=[
                ('cd', models.CharField(help_text='国コード', max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='国名(英語表記)', max_length=200)),
                ('detail', models.CharField(default='', help_text='詳細', max_length=200)),
                ('memo', models.CharField(default='', help_text='メモ（内部用）', max_length=500)),
            ],
            options={
                'db_table': 'verify',
            },
        ),
        migrations.AlterUniqueTogether(
            name='currency',
            unique_together={('country', 'cd', 'name')},
        ),
    ]
